name: ubuntu-latest-SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup upterm session
      uses: olifre/action-upterm@v1
      with:
        limit-access-to-actor: true
